version: '{build}'

os: Visual Studio 2015

cache:
  - x86_64-4.9.2-release-win32-seh-rt_v4-rev4.7z
  - hdf5-1.8.17-win32-vs2015-shared.zip

platform:
  - x64
  
environment:
  matrix:
  - HDF5_DIR: "C:\\Program Files (x86)\\HDF_Group\\HDF5\\1.8.17"
    HDF5_URL: https://support.hdfgroup.org/ftp/HDF5/current/bin/windows/extra/hdf5-1.8.17-win32-vs2015-shared.zip
    HDF5_ARCHIVE: hdf5-1.8.17-win32-vs2015-shared.zip
  
install:
  - if not exist "%HDF5_ARCHIVE%" appveyor DownloadFile "%HDF5_URL%" -FileName "%HDF5_ARCHIVE%"
  - 7z x -y "%HDF5_ARCHIVE%" > nul
  - cd hdf5
  - msiexec /i HDF5-1.8.17-win32.msi /quiet 
  - set Path=%path%;C:\MinGW\msys\1.0\bin;C:\MinGW\bin
  - mingw-get update
  - mingw-get install mingw-utils
  - ls 
  - cd "C:\Program Files (x86)\HDF_Group\HDF5\1.8.17\lib"
  - ls
  - C:\MinGW\msys\1.0\bin\sh C:\projects\amici\scripts\patch-hdf5.sh
  - cd "C:\projects\amici"

before_build:

build_script:
  - ps: .\scripts\build-mingw.ps1