version: '{build}'

os: 
  - Visual Studio 2015

cache:
  - x86_64-4.9.2-release-win32-seh-rt_v4-rev4.7z

platform:
  - x64
  
environment:
  matrix:
  - Compiler: mingw
  
install:

before_build:
  
build_script:
  - ps: |
    if ($env:Compiler -eq "mingw") {
      .\scripts\build-mingw.ps1
    } else {
      .\scripts\build-msvs.ps1
    }