version: '{build}'

os: 
  - Visual Studio 2015

cache:
  - x86_64-4.9.2-release-win32-seh-rt_v4-rev4.7z

platform:
  - x64
  
environment:
  matrix:
  - Compiler: mingw
    MINGW_DIR: mingw64
    MINGW_URL: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/4.9.2/threads-win32/seh/x86_64-4.9.2-release-win32-seh-rt_v4-rev4.7z/download
    MINGW_ARCHIVE: x86_64-4.9.2-release-win32-seh-rt_v4-rev4.7z
    WINDBG_DIR: '%ProgramFiles(x86)%\Windows Kits\8.1\Debuggers\x64'
  
install:
  - if not exist "%MINGW_ARCHIVE%" appveyor DownloadFile "%MINGW_URL%" -FileName "%MINGW_ARCHIVE%"
  - 7z x -y "%MINGW_ARCHIVE%" > nul
  
before_build:
  -ps: set Path=%CD%\%MINGW_DIR%\bin;%Path%

build_script:
  - ps: powershell -File ".\scripts\build-mingw.ps1"
