# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: documentation/conf.py
  fail_on_warning: True

formats:
  - pdf

python:
  install:
    - requirements: documentation/rtd_requirements.txt
build:
  os: "ubuntu-22.04"
  apt_packages:
    - libatlas-base-dev
    - swig
  tools:
    python: "3.11"
