# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: documentation/conf.py
  fail_on_warning: True

formats:
  - pdf

python:
  install:
    - requirements: documentation/rtd_requirements.txt
    - requirements: documentation/rtd_requirements2.txt
build:
  os: "ubuntu-20.04"
  apt_packages:
    # for custom doxygen
    - libclang-cpp9
    - libclang1-9
  tools:
    python: "3.8"
