var annotated_dup =
[
    [ "amici", null, [
      [ "AbstractModel", "classamici_1_1_abstract_model.html", "classamici_1_1_abstract_model" ],
      [ "AmiciApplication", "classamici_1_1_amici_application.html", "classamici_1_1_amici_application" ],
      [ "AmiException", "classamici_1_1_ami_exception.html", "classamici_1_1_ami_exception" ],
      [ "AmiVector", "classamici_1_1_ami_vector.html", "classamici_1_1_ami_vector" ],
      [ "AmiVectorArray", "classamici_1_1_ami_vector_array.html", "classamici_1_1_ami_vector_array" ],
      [ "BackwardProblem", "classamici_1_1_backward_problem.html", "classamici_1_1_backward_problem" ],
      [ "ConditionContext", "classamici_1_1_condition_context.html", "classamici_1_1_condition_context" ],
      [ "ContextManager", "classamici_1_1_context_manager.html", "classamici_1_1_context_manager" ],
      [ "CvodeException", "classamici_1_1_cvode_exception.html", "classamici_1_1_cvode_exception" ],
      [ "ExpData", "classamici_1_1_exp_data.html", "classamici_1_1_exp_data" ],
      [ "FinalStateStorer", "classamici_1_1_final_state_storer.html", "classamici_1_1_final_state_storer" ],
      [ "ForwardProblem", "classamici_1_1_forward_problem.html", "classamici_1_1_forward_problem" ],
      [ "IDAException", "classamici_1_1_i_d_a_exception.html", "classamici_1_1_i_d_a_exception" ],
      [ "IntegrationFailure", "classamici_1_1_integration_failure.html", "classamici_1_1_integration_failure" ],
      [ "IntegrationFailureB", "classamici_1_1_integration_failure_b.html", "classamici_1_1_integration_failure_b" ],
      [ "Model", "classamici_1_1_model.html", "classamici_1_1_model" ],
      [ "Model_DAE", "classamici_1_1_model___d_a_e.html", "classamici_1_1_model___d_a_e" ],
      [ "Model_ODE", "classamici_1_1_model___o_d_e.html", "classamici_1_1_model___o_d_e" ],
      [ "ModelContext", "classamici_1_1_model_context.html", "classamici_1_1_model_context" ],
      [ "ModelState", "structamici_1_1_model_state.html", "structamici_1_1_model_state" ],
      [ "NewtonFailure", "classamici_1_1_newton_failure.html", "classamici_1_1_newton_failure" ],
      [ "NewtonSolver", "classamici_1_1_newton_solver.html", "classamici_1_1_newton_solver" ],
      [ "NewtonSolverDense", "classamici_1_1_newton_solver_dense.html", "classamici_1_1_newton_solver_dense" ],
      [ "NewtonSolverIterative", "classamici_1_1_newton_solver_iterative.html", "classamici_1_1_newton_solver_iterative" ],
      [ "NewtonSolverSparse", "classamici_1_1_newton_solver_sparse.html", "classamici_1_1_newton_solver_sparse" ],
      [ "ReturnData", "classamici_1_1_return_data.html", "classamici_1_1_return_data" ],
      [ "SetupFailure", "classamici_1_1_setup_failure.html", "classamici_1_1_setup_failure" ],
      [ "SimulationState", "structamici_1_1_simulation_state.html", "structamici_1_1_simulation_state" ],
      [ "Solver", "classamici_1_1_solver.html", "classamici_1_1_solver" ],
      [ "SteadystateProblem", "classamici_1_1_steadystate_problem.html", "classamici_1_1_steadystate_problem" ],
      [ "SUNLinSolBand", "classamici_1_1_s_u_n_lin_sol_band.html", "classamici_1_1_s_u_n_lin_sol_band" ],
      [ "SUNLinSolDense", "classamici_1_1_s_u_n_lin_sol_dense.html", "classamici_1_1_s_u_n_lin_sol_dense" ],
      [ "SUNLinSolKLU", "classamici_1_1_s_u_n_lin_sol_k_l_u.html", "classamici_1_1_s_u_n_lin_sol_k_l_u" ],
      [ "SUNLinSolPCG", "classamici_1_1_s_u_n_lin_sol_p_c_g.html", "classamici_1_1_s_u_n_lin_sol_p_c_g" ],
      [ "SUNLinSolSPBCGS", "classamici_1_1_s_u_n_lin_sol_s_p_b_c_g_s.html", "classamici_1_1_s_u_n_lin_sol_s_p_b_c_g_s" ],
      [ "SUNLinSolSPFGMR", "classamici_1_1_s_u_n_lin_sol_s_p_f_g_m_r.html", "classamici_1_1_s_u_n_lin_sol_s_p_f_g_m_r" ],
      [ "SUNLinSolSPGMR", "classamici_1_1_s_u_n_lin_sol_s_p_g_m_r.html", "classamici_1_1_s_u_n_lin_sol_s_p_g_m_r" ],
      [ "SUNLinSolSPTFQMR", "classamici_1_1_s_u_n_lin_sol_s_p_t_f_q_m_r.html", "classamici_1_1_s_u_n_lin_sol_s_p_t_f_q_m_r" ],
      [ "SUNLinSolWrapper", "classamici_1_1_s_u_n_lin_sol_wrapper.html", "classamici_1_1_s_u_n_lin_sol_wrapper" ],
      [ "SUNMatrixWrapper", "classamici_1_1_s_u_n_matrix_wrapper.html", "classamici_1_1_s_u_n_matrix_wrapper" ],
      [ "SUNNonLinSolFixedPoint", "classamici_1_1_s_u_n_non_lin_sol_fixed_point.html", "classamici_1_1_s_u_n_non_lin_sol_fixed_point" ],
      [ "SUNNonLinSolNewton", "classamici_1_1_s_u_n_non_lin_sol_newton.html", "classamici_1_1_s_u_n_non_lin_sol_newton" ],
      [ "SUNNonLinSolWrapper", "classamici_1_1_s_u_n_non_lin_sol_wrapper.html", "classamici_1_1_s_u_n_non_lin_sol_wrapper" ]
    ] ],
    [ "amidata", "classamidata.html", "classamidata" ],
    [ "amievent", "classamievent.html", "classamievent" ],
    [ "amifun", "classamifun.html", "classamifun" ],
    [ "amimodel", "classamimodel.html", "classamimodel" ],
    [ "amioption", "classamioption.html", "classamioption" ],
    [ "amised", "classamised.html", "classamised" ],
    [ "optsym", "classoptsym.html", "classoptsym" ]
];