version: '{build}'

os: Visual Studio 2015

cache:
  - x86_64-4.9.2-release-win32-seh-rt_v4-rev4.7z
  - hdf5-1.8.17-win64-vs2015-shared.zip

platform:
  - x64
  
branches:
  only:
    - master
    - staging
  
environment:
  matrix:
  - compiler: mingw
    MINGW_DIR: mingw64
    MINGW_URL: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/4.9.2/threads-win32/seh/x86_64-4.9.2-release-win32-seh-rt_v4-rev4.7z/download
    MINGW_ARCHIVE: x86_64-4.9.2-release-win32-seh-rt_v4-rev4.7z
    HDF5_URL: https://support.hdfgroup.org/ftp/HDF5/current/bin/windows/extra/hdf5-1.8.17-win64-vs2015-shared.zip
    HDF5_ARCHIVE: hdf5-1.8.17-win64-vs2015-shared.zip
  
install:
  - if not exist "%MINGW_ARCHIVE%" appveyor DownloadFile "%MINGW_URL%" -FileName "%MINGW_ARCHIVE%"
  - if not exist "%HDF5_ARCHIVE%" appveyor DownloadFile "%HDF5_URL%" -FileName "%HDF5_ARCHIVE%"
  - 7z x -y "%MINGW_ARCHIVE%" > nul
  - 7z x -y "%HDF5_ARCHIVE%" > nul
  - cd hdf5
  - msiexec /i HDF5-1.8.17-win64.msi /quiet 
  - cd "C:\Program Files\HDF_Group\HDF5\1.8.17\lib"
  - C:\MinGW\msys\1.0\bin\sh C:\projects\amici\scripts\patch-hdf5.sh
  - cd "C:\projects\amici"

before_build:
  - set "Path=%CD%\%MINGW_DIR%\bin;C:\Program Files\HDF_Group\HDF5\1.8.17;%Path%"

build_script:
  - ps: .\scripts\build-mingw.ps1