# see https://docs.codecov.com/docs/codecovyml-reference

fixes:
  # https://docs.codecov.com/docs/fixing-paths
  - "build/venv/lib/python[0-9.]+/site-packages/::python/"
  - "python/sdist/build/temp_amici/CMakeFiles/amici.dir/src/::src/"
  - "build/CMakeFiles/amici.dir/src/::src/"
codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

ignore:
  - "tests/*"
  - "tests/**/*"
  - "build/tests/**"
  - "amici_models/**"

flags:
  python:
    carryforward: false
  cpp:
    carryforward: false
  petab:
    carryforward: false
  sbmlsuite:
    paths:
      - "python/amici/sbml_import.py"
      - "python/amici/de_export.py"
    carryforward: true
