fixes:
  - "build/venv/lib/python3.9/site-packages/::python/"
  - "build/venv/lib/python3.10/site-packages/::python/"
  - "build/venv/lib/python3.11/site-packages/::python/"

codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

ignore:
  - "tests/*"
  - "tests/**/*"

flags:
  python:
    carryforward: false
  cpp:
    carryforward: false
  petab:
    carryforward: false
  sbmlsuite:
    paths:
      - "python/amici/sbml_import.py"
      - "python/amici/de_export.py"
    carryforward: true
