var searchData=
[
  ['makeevents_1423',['makeEvents',['../classamimodel.html#a4d4b20c81af6d7ed977b6b818c7b22db',1,'amimodel']]],
  ['makesyms_1424',['makeSyms',['../classamimodel.html#a5aba9155145df4b3f70bfec887c25af9',1,'amimodel']]],
  ['mexfunction_1425',['mexFunction',['../interface__matlab_8cpp.html#a6a215cbfde54f82a3ce599228fc3fce5',1,'interface_matlab.cpp']]],
  ['minus_1426',['minus',['../classamici_1_1_ami_vector.html#a19ad39a609bfc430ed6f7992e841b024',1,'amici::AmiVector']]],
  ['model_1427',['Model',['../classamici_1_1_model.html#a02c5be8897be20f1384a14e062b608c2',1,'amici::Model::Model()=default'],['../classamici_1_1_model.html#a6fc7d7ca95d2685dbe94649bc9f2cd7a',1,'amici::Model::Model(int nx_rdata, int nxtrue_rdata, int nx_solver, int nxtrue_solver, int nx_solver_reinit, int ny, int nytrue, int nz, int nztrue, int ne, int nJ, int nw, int ndwdx, int ndwdp, int ndxdotdw, std::vector&lt; int &gt; ndJydy, int nnz, int ubw, int lbw, amici::SecondOrderMode o2mode, const std::vector&lt; amici::realtype &gt; &amp;p, std::vector&lt; amici::realtype &gt; k, const std::vector&lt; int &gt; &amp;plist, std::vector&lt; amici::realtype &gt; idlist, std::vector&lt; int &gt; z2event, bool pythonGenerated=false, int ndxdotdp_explicit=0, int ndxdotdp_implicit=0)']]],
  ['model_5fdae_1428',['Model_DAE',['../classamici_1_1_model___d_a_e.html#a7da74e90fc0e61bda8ee186606870fe6',1,'amici::Model_DAE::Model_DAE()=default'],['../classamici_1_1_model___d_a_e.html#a51ce09d26f66e65b969ab443c7c8deb2',1,'amici::Model_DAE::Model_DAE(const int nx_rdata, const int nxtrue_rdata, const int nx_solver, const int nxtrue_solver, const int nx_solver_reinit, const int ny, const int nytrue, const int nz, const int nztrue, const int ne, const int nJ, const int nw, const int ndwdx, const int ndwdp, const int ndxdotdw, std::vector&lt; int &gt; ndJydy, const int nnz, const int ubw, const int lbw, const SecondOrderMode o2mode, std::vector&lt; realtype &gt; const &amp;p, std::vector&lt; realtype &gt; const &amp;k, std::vector&lt; int &gt; const &amp;plist, std::vector&lt; realtype &gt; const &amp;idlist, std::vector&lt; int &gt; const &amp;z2event, const bool pythonGenerated=false, const int ndxdotdp_explicit=0, const int ndxdotdp_implicit=0)']]],
  ['model_5fode_1429',['Model_ODE',['../classamici_1_1_model___o_d_e.html#afa75ea13c14a0222d1dfd25b2846ecbb',1,'amici::Model_ODE::Model_ODE()=default'],['../classamici_1_1_model___o_d_e.html#af20b2702d68028199dec171ec47b5711',1,'amici::Model_ODE::Model_ODE(const int nx_rdata, const int nxtrue_rdata, const int nx_solver, const int nxtrue_solver, const int nx_solver_reinit, const int ny, const int nytrue, const int nz, const int nztrue, const int ne, const int nJ, const int nw, const int ndwdx, const int ndwdp, const int ndxdotdw, std::vector&lt; int &gt; ndJydy, const int nnz, const int ubw, const int lbw, const SecondOrderMode o2mode, std::vector&lt; realtype &gt; const &amp;p, std::vector&lt; realtype &gt; const &amp;k, std::vector&lt; int &gt; const &amp;plist, std::vector&lt; realtype &gt; const &amp;idlist, std::vector&lt; int &gt; const &amp;z2event, const bool pythonGenerated=false, const int ndxdotdp_explicit=0, const int ndxdotdp_implicit=0)']]],
  ['modelcontext_1430',['ModelContext',['../classamici_1_1_model_context.html#a8945926a0fd90f4b14aa908ee9bfada2',1,'amici::ModelContext']]],
  ['multiply_1431',['multiply',['../classamici_1_1_s_u_n_matrix_wrapper.html#af2c987388fcb260819e5279e0ab3d556',1,'amici::SUNMatrixWrapper::multiply(N_Vector c, const_N_Vector b) const'],['../classamici_1_1_s_u_n_matrix_wrapper.html#a886b96fde5c5d4caf09286d59666a731',1,'amici::SUNMatrixWrapper::multiply(gsl::span&lt; realtype &gt; c, gsl::span&lt; const realtype &gt; b) const'],['../classamici_1_1_s_u_n_matrix_wrapper.html#aab1c4ef6afa45bc7c624078daba2ed00',1,'amici::SUNMatrixWrapper::multiply(N_Vector c, const N_Vector b, gsl::span&lt; const int &gt; cols, bool transpose) const'],['../classamici_1_1_s_u_n_matrix_wrapper.html#a11136ec9b9f1fc32464f8677e46e8355',1,'amici::SUNMatrixWrapper::multiply(gsl::span&lt; realtype &gt; c, gsl::span&lt; const realtype &gt; b, gsl::span&lt; const int &gt; cols, bool transpose) const']]],
  ['mxarraytovector_1432',['mxArrayToVector',['../interface__matlab_8cpp.html#af8f91dbb6a395a9907c59dd92991ec18',1,'amici']]]
];
