var searchData=
[
  ['makeevents_1465',['makeEvents',['../classamimodel.html#a4d4b20c81af6d7ed977b6b818c7b22db',1,'amimodel']]],
  ['makesyms_1466',['makeSyms',['../classamimodel.html#a5aba9155145df4b3f70bfec887c25af9',1,'amimodel']]],
  ['matrix_5fid_1467',['matrix_id',['../classamici_1_1_s_u_n_matrix_wrapper.html#afe8237c9c203c573e1618a15782763c0',1,'amici::SUNMatrixWrapper']]],
  ['minus_1468',['minus',['../classamici_1_1_ami_vector.html#a19ad39a609bfc430ed6f7992e841b024',1,'amici::AmiVector']]],
  ['model_1469',['Model',['../classamici_1_1_model.html#a02c5be8897be20f1384a14e062b608c2',1,'amici::Model::Model()=default'],['../classamici_1_1_model.html#aba0736dfa620bfc2276adcbde95caf2e',1,'amici::Model::Model(int nx_rdata, int nxtrue_rdata, int nx_solver, int nxtrue_solver, int nx_solver_reinit, int ny, int nytrue, int nz, int nztrue, int ne, int nJ, int nw, int ndwdx, int ndwdp, int ndwdw, int ndxdotdw, std::vector&lt; int &gt; ndJydy, int nnz, int ubw, int lbw, amici::SecondOrderMode o2mode, const std::vector&lt; amici::realtype &gt; &amp;p, std::vector&lt; amici::realtype &gt; k, const std::vector&lt; int &gt; &amp;plist, std::vector&lt; amici::realtype &gt; idlist, std::vector&lt; int &gt; z2event, bool pythonGenerated=false, int ndxdotdp_explicit=0, int ndxdotdx_explicit=0, int w_recursion_depth=0)']]],
  ['model_5fdae_1470',['Model_DAE',['../classamici_1_1_model___d_a_e.html#a7da74e90fc0e61bda8ee186606870fe6',1,'amici::Model_DAE::Model_DAE()=default'],['../classamici_1_1_model___d_a_e.html#ac0be07e15db73af55651ad93487b54a9',1,'amici::Model_DAE::Model_DAE(const int nx_rdata, const int nxtrue_rdata, const int nx_solver, const int nxtrue_solver, const int nx_solver_reinit, const int ny, const int nytrue, const int nz, const int nztrue, const int ne, const int nJ, const int nw, const int ndwdx, const int ndwdp, const int ndwdw, const int ndxdotdw, std::vector&lt; int &gt; ndJydy, const int nnz, const int ubw, const int lbw, const SecondOrderMode o2mode, std::vector&lt; realtype &gt; const &amp;p, std::vector&lt; realtype &gt; const &amp;k, std::vector&lt; int &gt; const &amp;plist, std::vector&lt; realtype &gt; const &amp;idlist, std::vector&lt; int &gt; const &amp;z2event, const bool pythonGenerated=false, const int ndxdotdp_explicit=0)']]],
  ['model_5fode_1471',['Model_ODE',['../classamici_1_1_model___o_d_e.html#afa75ea13c14a0222d1dfd25b2846ecbb',1,'amici::Model_ODE::Model_ODE()=default'],['../classamici_1_1_model___o_d_e.html#a36029851049871e52e1a8df437ee3c06',1,'amici::Model_ODE::Model_ODE(const int nx_rdata, const int nxtrue_rdata, const int nx_solver, const int nxtrue_solver, const int nx_solver_reinit, const int ny, const int nytrue, const int nz, const int nztrue, const int ne, const int nJ, const int nw, const int ndwdx, const int ndwdp, const int ndwdw, const int ndxdotdw, std::vector&lt; int &gt; ndJydy, const int nnz, const int ubw, const int lbw, const SecondOrderMode o2mode, std::vector&lt; realtype &gt; const &amp;p, std::vector&lt; realtype &gt; const &amp;k, std::vector&lt; int &gt; const &amp;plist, std::vector&lt; realtype &gt; const &amp;idlist, std::vector&lt; int &gt; const &amp;z2event, const bool pythonGenerated=false, const int ndxdotdp_explicit=0, const int ndxdotdx_explicit=0, const int w_recursion_depth=0)']]],
  ['modelcontext_1472',['ModelContext',['../classamici_1_1_model_context.html#a8945926a0fd90f4b14aa908ee9bfada2',1,'amici::ModelContext']]],
  ['multiply_1473',['multiply',['../classamici_1_1_s_u_n_matrix_wrapper.html#af2c987388fcb260819e5279e0ab3d556',1,'amici::SUNMatrixWrapper::multiply(N_Vector c, const_N_Vector b) const'],['../classamici_1_1_s_u_n_matrix_wrapper.html#a886b96fde5c5d4caf09286d59666a731',1,'amici::SUNMatrixWrapper::multiply(gsl::span&lt; realtype &gt; c, gsl::span&lt; const realtype &gt; b) const'],['../classamici_1_1_s_u_n_matrix_wrapper.html#aab1c4ef6afa45bc7c624078daba2ed00',1,'amici::SUNMatrixWrapper::multiply(N_Vector c, const N_Vector b, gsl::span&lt; const int &gt; cols, bool transpose) const'],['../classamici_1_1_s_u_n_matrix_wrapper.html#a11136ec9b9f1fc32464f8677e46e8355',1,'amici::SUNMatrixWrapper::multiply(gsl::span&lt; realtype &gt; c, gsl::span&lt; const realtype &gt; b, gsl::span&lt; const int &gt; cols, bool transpose) const']]]
];
