function out = dxdotdp_model_dirac_adjoint_hessVecProd(t,x,p,k)
%DXDOTDP_MODEL_DIRAC_ADJOINT_HESSVECPROD
%    out = DXDOTDP_MODEL_DIRAC_ADJOINT_HESSVECPROD(T,X,P,K)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    16-Aug-2016 11:34:38

out = sparse([],[],[],2,4,3);
out(1) = -x(1);
out(6) = x(1);
out(8) = -x(2);
