function out = J_model_dirac_adjoint_hessVecProd(t,x,p,k)
%J_MODEL_DIRAC_ADJOINT_HESSVECPROD
%    out = J_MODEL_DIRAC_ADJOINT_HESSVECPROD(T,X,P,K)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    16-Aug-2016 11:34:38

out = sparse([],[],[],2,2,3);
out(1) = -p(1);
out(2) = p(3);
out(4) = -p(4);
