oldpath = addpath(genpath('.'));
example_events
example_dirac
example_dirac_adjoint
example_dirac_secondorder
example_dirac_secondorder_vectmult
example_adjoint
example_jakstat_adjoint
example_steadystate
example_nested_events
example_adjoint_hessian
example_dirac_adjoint_hessVecProd
example_jakstat_adjoint_hvp
example_robertson
example_neuron
example_calvetti
path(oldpath);
