#!/bin/bash
#
# Build Sundials
#
set -e

AMICI_PATH="`dirname \"$BASH_SOURCE\"`"
AMICI_PATH="`( cd \"$AMICI_PATH/..\" && pwd )`"

SUITESPARSE_ROOT="${AMICI_PATH}/SuiteSparse"
SUNDIALS_BUILD_PATH="${AMICI_PATH}/sundials/build/"

mkdir -p ${SUNDIALS_BUILD_PATH}
cd ${SUNDIALS_BUILD_PATH}

cmake -DCMAKE_INSTALL_PREFIX="${SUNDIALS_BUILD_PATH}" \
-DBUILD_ARKODE=OFF \
-DBUILD_CVODE=OFF \
-DBUILD_IDA=OFF \
-DBUILD_KINSOL=OFF \
-DBUILD_SHARED_LIBS=ON \
-DBUILD_STATIC_LIBS=ON \
-DEXAMPLES_ENABLE=OFF \
-DEXAMPLES_INSTALL=OFF \
-DKLU_ENABLE=ON \
-DKLU_LIBRARY_DIR="${SUITESPARSE_ROOT}/lib" \
-DKLU_INCLUDE_DIR="${SUITESPARSE_ROOT}/include" \
..

make
make install

# Set DYLD_LIBRARY_PATH for osx
ENV_FILE=${AMICI_PATH}/scripts/env.sh
touch ${ENV_FILE} && echo export DYLD_LIBRARY_PATH=\"\${DYLD_LIBRARY_PATH}:${SUNDIALS_BUILD_PATH}/lib\" >> ${ENV_FILE}
