function out = J_model_jakstat_adjoint_hvp(t,x,p,k)
%J_MODEL_JAKSTAT_ADJOINT_HVP
%    out = J_MODEL_JAKSTAT_ADJOINT_HVP(T,X,P,K)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    31-Aug-2016 16:00:20

out = sparse([],[],[],9,9,18);
out(1) = -p(1)*am_spline_pos(t, 5.0, 0.0, p(6), 5.0, p(7), 10.0, p(8), 20.0, p(9), 60.0, p(10), 0.0, 0);
out(2) = p(1)*am_spline_pos(t, 5.0, 0.0, p(6), 5.0, p(7), 10.0, p(8), 20.0, p(9), 60.0, p(10), 0.0, 0);
out(11) = -4*p(2)*x(2);
out(12) = 2*p(2)*x(2);
out(21) = -p(3);
out(22) = (k(1)*p(3))/k(2);
out(31) = -p(4);
out(32) = 2*p(4);
out(41) = -p(4);
out(42) = p(4);
out(51) = -p(4);
out(52) = p(4);
out(61) = -p(4);
out(62) = p(4);
out(71) = -p(4);
out(72) = p(4);
out(73) = (k(2)*p(4))/k(1);
out(81) = -p(4);
