name: Doxygen
on: [push]

jobs:
  build:
    name: Ubuntu

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - run: git fetch --prune --unshallow

    - run: echo "::set-env name=AMICI_DIR::$(pwd)"

    - name: apt
      run: |
        sudo apt-get update \
          && sudo apt-get install -y \
          bison \
          ragel \
          graphviz \
          texlive-latex-recommended

    - name: Build doxygen
      run: |
        sudo scripts/downloadAndBuildDoxygen.sh

    - name: Run doxygen
      run: |
        scripts/run-doxygen.sh
        
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.5.7
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: doc # The folder the action should deploy.
