name: Doxygen
on: [push]

jobs:
  build:
    name: Ubuntu

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - run: git fetch --prune --unshallow

    - run: echo "::set-env name=AMICI_DIR::$(pwd)"

    - name: apt
      run: |
        sudo apt-get update \
          && sudo apt-get install -y bison ragel graphviz
          
    - name: tinytex
      run: |
        wget -qO- "https://yihui.org/gh/tinytex/tools/install-unx.sh" | sh

    - name: Build doxygen
      run: |
        sudo scripts/downloadAndBuildDoxygen.sh

    - name: Run doxygen
      run: |
        scripts/run-doxygen.sh
