name: Installation
on: [push]

jobs:
  build:
    name: Archive Install

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - run: git fetch --prune --unshallow

    - run: echo "::set-env name=AMICI_DIR::$(pwd)"
    - run: echo "::set-env name=BNGPATH::${AMICI_DIR}/ThirdParty/BioNetGen-2.3.2"

    # install amici dependencies
    - name: apt
      run: |
        sudo apt-get update \
          && sudo apt-get install -y \
            cmake \
            g++ \
            libatlas-base-dev \
            libboost-serialization-dev \
            libhdf5-serial-dev \
            swig

    - name: Build suitesparse
      run: |
        scripts/buildSuiteSparse.sh

    - name: Build sundials
      run: |
        scripts/buildSundials.sh

    - name: Build cpputest
      run: |
        scripts/buildCpputest.sh

    - name: Build cpputest
      run: |
        scripts/buildBNGL.sh

    - name: Build AMICI
      run: |
        pip3 install numpy \
        && scripts/buildAmici.sh
    
    - name: Install python archive
      run: |
        scripts/installAmiciArchive.sh
